# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
     - uses: actions/checkout@v2
     - name: "Set up JDK 1.8"
       uses: actions/setup-java@v1
       with: 
        java-version: 1.8
     - name: "Cache Maven packages"
       uses: actions/cache@v2
       with: 
        path: ~/.m2
        key: "${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}"
        restore-keys: "${{ runner.os }}-m2"
 
     - name: "Build with Maven"
       run: "mvn -B package --file pom.xml"
     - name: SonarCloud Scan
  # You may pin to the exact commit or the version.
  # uses: SonarSource/sonarcloud-github-action@f4c6e4d91ea9785ec823eaeed459042606123402
       uses: SonarSource/sonarcloud-github-action@v1.4
       with:
    # Additional arguments to the sonarcloud scanner
#         args: 
#             -Dsonar.tests=tests/
#             -Dsonar.verbose=true
    # Set the sonar.projectBaseDir analysis property
        projectBaseDir: .
  
